# Example config file
# Fore more detail, see src/config.rs

db_path = "data/sled"
channel_size = 15
log_level = "info"

[caster_feed]
interval = 2.0
urls = [ "http://localhost:8080/test.xml" ]

[caster_crates]
interval = 60.0
crates = [ "foo", "bar" ]

[consumer_telegram]
api_token = "0000000000:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
content_max_length = 0
chats = [ -10000000000 ]